version = 2

[module]
type = "android-app"
name = "app"
languageLevel = "KOTLIN_1_9"
output = "build/classes"

[sourceSets.main]
scope = "IMPLEMENTATION"
assets = ["src/main/assets"]
java = ["src/main/java"]
res = ["src/main/res"]

[android]
namespace = "fjv.dic.so"
compileSdk = 34
minSdk = 24
targetSdk = 36
manifest = "src/main/AndroidManifest.xml"
versionCode = 1
versionName = "1.0"
isApplication = true
